services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      OPENAI_API_KEY: ${OPENAI_KEY}
      DATABASE_URL: ${DATABASE_URL}
      WUZAPI_TOKEN: ${WUZAPI_TOKEN:-iamhipster}
    depends_on:
      postgres: # If your main backend app (not just webhook handler) needs the main DB
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/initial_schema.sql:/docker-entrypoint-initdb.d/initial_schema.sql # Mount the schema file
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: iamhipster
      POSTGRES_DB: chatwithoats
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d chatwithoats"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres_wuzapi:
    image: postgres:16-alpine
    ports:
      - "5433:5432" # New port for wuzapi's postgres
    volumes:
      - postgres_wuzapi_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: iamhipster
      POSTGRES_DB: wuzapi_db # New database name for wuzapi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d wuzapi_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  wuzapi:
    build:
      context: ./wuzapi
      dockerfile: Dockerfile
    ports:
      - "8081:8080" # Host port 8081 maps to container port 8080
    volumes:
      - wuzapi_ssl:/app/ssl
      - wuzapi_dbdata:/app/dbdata
    environment:
      WUZAPI_ADMIN_TOKEN: UsQSyX7KMf5QNSe1VMgZHqc6RZeXwqn1Tt0UuquKA
      WUZAPI_WEBHOOK_TIMEOUT: 30
      WUZAPI_MAX_RETRIES: 3
      WUZAPI_RETRY_DELAY: 5
      DB_HOST: postgres_wuzapi # Point to the new wuzapi postgres service
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: iamhipster
      DB_NAME: wuzapi_db # Use the new database name
      TZ: UTC
    command: ["/app/server", "-address", "0.0.0.0", "-logtype", "json", "-admintoken", "${WUZAPI_ADMIN_TOKEN}"]
    restart: unless-stopped
    depends_on:
      postgres_wuzapi: # Depend on the new wuzapi postgres service
        condition: service_healthy

volumes:
  postgres_data:
  postgres_wuzapi_data: # New volume for wuzapi's postgres
  wuzapi_ssl:
  wuzapi_dbdata: 